### ISSUE TITLE
Support for Windows Server 2016 and ADFS

### ISSUE THREAD

**Issue by ravicini** [psignoret/aad-sso-wordpress#104]
ADFS on Windows Server 2016 added some neat extensions like OpenIDConnect and complete OAuth2.

We do have a shared environment and tried to get your plugin up and running with Windows Server 2016 - and succeeded. ;)

Now I'd like to open a discussion if and how we want to integrate support for Windows Server 2016 to your plugin.

You see the changes in the following commit (not ready to integrate, but working): https://github.com/MultimediaSolutionsAg/aad-sso-wordpress/commit/3204f8c63dd23434e1ccd151982a74a4ba0087a8

Current Restrictions:
* Only works for Windows Server 2016
* Windows Server 2016 does not support a neat Graph API for group queries, so the group functionality is not supported.

I see those 2 different possibilities to integrate the support:
* Settings flag: *is_win_server_2106* and disable the group functionality then
* Trying to implement the group functionality with the Windows Server 2016

**Comment by psignoret** [comment]
Thanks for showing interest in this. (Sorry for delayed response.)

Integrating directly with AD FS isn't really the intent of this plugin. (I deliberately named it "Azure AD", to clarify it was not a generic OpenID Connect plugin.) Moving forward, I expect more organization will be looking to tie applications to cloud providers (e.g. Azure AD), instead of adding on-prem dependencies (AD FS).

That said, since it's such a trivial change, I see no no reason why we can't have this as an "advanced" feature. If you have a pull request, I'd be more an happy to review it.
