### ISSUE TITLE
[Question] Windows Security

### ISSUE THREAD

**Issue by ChainsawBaby** [psignoret/aad-sso-wordpress#133]
I'm trying to set this up for a client, and they have the possibility to use their AD user to login on their computers, hence the SSO... 😜

I'm not familiar with Azure AD, but I managed to set it up for our Office 365 subscription, and AAD SSO login works.
And I think I got it somewhat setup on their AD too.
They click the link to login with AD, and is sent to adfs.domain.com (Active Directory Federation Services), and they manage to login there.

But then they got a popup on their Windows machine,
![https://i.bratteng.xyz/0yfCO7aFwp.png](https://i.bratteng.xyz/0yfCO7aFwp.png)

What do they put in there? Their email and password?
And what settings should I have in AAD SSO plugin?
This is what I have currently:
![https://i.bratteng.xyz/r8WTw7kCTN.png](https://i.bratteng.xyz/r8WTw7kCTN.png)

In the OpenID Connect configuration endpoint setting, I have replaced common with the clients Tenant ID

**Comment by psignoret** [comment]
Is their domain name in Azure AD already federated with AD FS? What happens when their users try to sign in to https://myapps.microsoft.com?

In general, it doesn't matter whether or not the Azure AD tenant is federated to an on-prem AD FS (por other identity provider). As long as Azure AD is in the middle, this plugin will work.

How you set the settings depends on what experience you want to enable. If you can elaborate on what you're looking for?

**Comment by ChainsawBaby** [comment]
This is for an intranet, that is on the internet, so I have forced login on the site.
And the client wants to use single sign-on with their Azure AD, so they don't need to remember yet another username and password.
The settings are just what I setup with my AD, and I got it to work

**Comment by ChainsawBaby** [comment]
Huh, so the client managed to log in now. Only thing I got them to change was the App ID URI, because it had been reset to a Microsoft link for some reason

**Comment by psignoret** [comment]
Ok, well, good to know it's working now! Feel free to re-open if this same issue comes back up.
