### ISSUE TITLE
Not adding new users automatically

### ISSUE THREAD

**Issue by cdeli** [psignoret/aad-sso-wordpress#138]
Set up everything per the final instructions with adding Group ID's and auto registration. No users being added in the user portal after they have successfully logged in and given permission to the application.

![image](https://user-images.githubusercontent.com/5881028/27300143-a45d0140-54fc-11e7-80cc-dc97d51d7043.png)

![image](https://user-images.githubusercontent.com/5881028/27300161-bd7e4d1e-54fc-11e7-9088-63c2cc6ac744.png)

**Comment by psignoret** [comment]
Are you sure the user has actually signed in successfully to the blog? It's highly unusual that WordPress would consider a user "signed in" if there weren't a backing entry in the database.

What is the experience for these users after they sign in? Can they navigate to their profile page?

**Comment by cdeli** [comment]
I was able to get the sign in to work properly after some work on my end, had a value wrong.

The problem I am running into now is that people in the group for Administrators are not being granted that level. They are instead being granted only subscriber. When I change the default to no group, it denys them access.

**Comment by cdeli** [comment]
Issue got worse. Now even though I manually added 3 admins, they reverted to subscriber level for some reason. I now have to rebuild my whole site because they are not getting the proper levels even though they are in the proper groups.

**Comment by psignoret** [comment]
This is the behaviour you would see if the users are not, in fact, members of the group you've given.

You should not be rebuilding your site just because your users got reverted to Subscriber. You can update the database manually to put your user back into Administrator (e.g. http://codingcyber.com/change-wordpress-user-role-database-using-phpmyadmin-3390/).

**Comment by cdeli** [comment]
I can assure you that I am part of the group I built. I copied the ID myself and verified it. The only part is that the group is not assigned to the application because we do not have AAD Basic.

**Comment by cdeli** [comment]
So no matter what I do the user always resets to subscriber. Now I have no administrators. What the hell do I do now??? I have changed the key 10 times and every time I log back in the user reverts from an Admin to a subscriber.

**Comment by bradkovach** [comment]
Based on your images, i see you're using the new Azure Portal...  My instances are using Office 365, instead of directory-synced accounts, but everything else that follows should be similar.

That being said, Azure AD should be relatively agnostic to **where** the users are from, just as long as they're in AD... @psignoret may have more insight.

I'm still getting used to the new Azure Portal so bear with me...

Visit this screen to make sure you have an app for your WordPress instance setup. 

Here are my WordPress installations...  Since each application has a different login URL, they need their own application registration with Azure AD.  The Application ID for your domain should be pasted into the Single Sign-on with Azure Active Directory config screen for the corresponding WordPress installation.

![image](https://user-images.githubusercontent.com/2043353/27360369-e93870ba-55dd-11e7-9e3f-b73ce07af5ba.png)

1. From the Azure AD > App registrations blade, select "New application registration"
2. Select a relevant name for to represent the WP installation, IE "WordPress production" or "Intranet DEV"
3. Enter the URL to the WordPress installation's wp-login.php page, for example `https://dev.contoso.com/wp-login.php`

![image](https://user-images.githubusercontent.com/2043353/27360470-893c7138-55de-11e7-8a42-3fe86411aafe.png)

4. Navigate to the Settings > Required permissions blade for your new application.  Click the Windows Azure Active Directory entry in the list and check "Sign in and read user profile" and "Read directory data"  Azure may alert about needing an Admin for "Read directory data".  We'll handle that in the next step...  This step is critical in allowing WordPress to check user-to-group memberships.  _If this isn't setup properly, the AADSSO Role Mapping will probably fail._

![image](https://user-images.githubusercontent.com/2043353/27360678-d6382bde-55df-11e7-8ea7-91a487ebc2fa.png)

5. Navigate to the "Settings > Keys" blade for your application.  Enter a Key description, assign the duration as you feel comfortable.  Click Save at the top of the blade and copy/paste the resulting client secret into the Single Sign-on with Azure Active Directory config screen for the corresponding WordPress installation.

![image](https://user-images.githubusercontent.com/2043353/27360657-b957ca88-55df-11e7-9bd3-9feabcfb42ee.png)

6. Ensure that the "Settings > Propertie"s blade values are as follows

| Setting        | Value                                             |
|----------------|---------------------------------------------------|
| Home Page URL  | *your WordPress installation's `wp-login.php` URL* |
| Logout URL     | *leave blank*                                        |
| Multi-tenanted | No                                                |

7. Ensure that the "Settings > Reply URLs" blade values list includes your WordPress installation's wp-login.php URL

**At this point, your WordPress installation should have the ability to authenticate as well as read and work with users in your Azure AD instance**

You can go to the "Azure AD > All groups" blade to manage the groups you intend to bind to WordPress. This plugin does not validate proper Guid entry, so make sure you aren't missing any characters at the beginning or end of the Group's Object ID.

**Comment by cdeli** [comment]
I have gone through everything and double checked everything. Still not reading that I am in the admin group even when I created a new group in azure.

**Comment by bradkovach** [comment]
@psignoret I don't have any installations synced with Active Directory, so I don't know if I can reproduce this.

@cdeli do you have access to a non-synced directory?

**Comment by cdeli** [comment]
You mean a group that is not synced on prem? I did make one was a test.

**Comment by psignoret** [comment]
@bradkovach I highly doubt this has anything to do with the fact that the directory is synced from AD. That's the most common use case.

@cdeli Can you send me an email at philippe.signoret@outlook.com, so that I can get some additional details from you? We'll report back here on what we find.

**Comment by cdeli** [comment]
I sent you an email @psignoret, however, I think we are on to something. Last night when I created the last comment I made a group that is not synced with on-prem AD and added my synced AD account to it. This morning I logged in with full rights as per the AAD Group Assignment that I had made. I am going to test some more with this, but it seems that the synced group is the problem from initial findings.

**Comment by psignoret** [comment]
@cdeli Though I'm happy it's working for you know, it's a but frustrating that we weren't able to figure out what the cause was. I think one thing that could use some improved debugging information (in additional to a group-picker experience to avoid copy-paste errors).

Feel free to re-open if you see this issue again.
