### ISSUE TITLE
Query about upgrading the plugin

### ISSUE THREAD

**Issue by chris18890** [psignoret/aad-sso-wordpress#153]
Hi there,

I've downlaodded the zip of the plugin from the GH link, & uploaded to the wordpress site via the "upload plugin" function & it appears (deactivated) as version 0.6.2, version 0.6.1 is still showing as active.  What'st he best way to upgrade the plugin? I assume it would be to copy the app ID & secret key to notepad, deactivate 0.6.1 & activate 0.6.2 & re-enter the details?

**Comment by psignoret** [comment]
@chris18890 Until I finally get this into the WordPress plugin directory (soon, I promise), you need to replace the existing plugin folder, most likely named `aad-sso-wordpress`.

The reason you're getting a duplicate entry is because the ZIP downloaded from GitHub names the folder `aad-sso-wordpress-master` (because it's the `master` branch of the repo). Even if the names matched, the WordPress would then throw an error about "folder already exists", so that's not really going to help you either.

If you're able to get access to the plugins directory directly (e.g. FTP, shell, etc.), that is the best approach.

**Comment by bradkovach** [comment]
In the mean time, you can set the plugin to use the GitHub repo for easy updates

```bash
$ cd wp-content/plugins/
$ git clone https://github.com/psignoret/aad-sso-wordpress.git aad-sso-wordpress
```

Then whenever there's an update, run:
```bash
$ cd wp-content/plugins/aad-sso-wordpress/
$ git pull
```

**Comment by psignoret** [comment]
Yes, of course, if you have command-line access and `git` available, @bradkovach describes the best approach.

**Comment by chris18890** [comment]
Hi both,

Thanks for this :)

While I have SSH access on my own servers, I don't on some of the client servers, just the WP admin interface! I was able to open the settings for 0.6.1, note the app ID & secret key & any other values, delactivate then delte the plugin, then upload 0.6.2 & set it up again using the same settings, seems to be working fine :)
