### ISSUE TITLE
Login Issue: User not registered

### ISSUE THREAD

**Issue by daveRendon** [psignoret/aad-sso-wordpress#161]
Hello, 

I just activated the plugin with default settings, however is not recognizing from wordpress: 

ERROR: The authenticated user 'live.com#' is not a registered user in this site.
ERROR: ANTIFORGERY_ID mismatch. Expecting {4}

Not sure if where does the prefix: live.com# is coming from, tried different users with same result

**Comment by psignoret** [comment]
The prefix is coming because you are signing in to your Azure AD tenant with a personal Microsoft Account (formerly known as "Live ID", hence the "live" prefix in the `unique_name` claim coming from Azure AD).

The first error (user not registered) means the plugin couldnt' find an existing WordPress user that matched that value. What WordPress field do you expect to match users on?

**Comment by daveRendon** [comment]
Thank for your quick response @psignoret 

I´m expecting to match the mail address, is there any additional configuration to match the mail address? I already set the "Field to match = Email Address" 

thank you

**Comment by keithnet** [comment]
Can you share how you resolved this?
