### ISSUE TITLE
The authenticated user is not a registered user in this site

### ISSUE THREAD

**Issue by aurramu** [psignoret/aad-sso-wordpress#221]
Hi,
I have signed up Azure using existing office 365 account .I have created the wordpress site in Azure and configured SSO with Azure AD in wordpress as per provided instructions.

Now the issue is getting " ERROR: The authenticated user '' is not a registered user in this site" message while sign to wordpress using xxx@xxx.onmicrosoft.com.

Please help me on this to fix this and also i would like know whether it is require Azure AD Premium or is it fine office 365 Azure AD for this integration?

Thanks
Ramu

**Comment by tibricel** [comment]
I am not using Azure Premium and its working fine. Are you using xxx@xxx.onmicrosoft.com the primary email alias for your users of Office365? If not and there primary email is user-email@company.com then they need to sign in with it instead. 

I would also create a Security group so only users in that group can access your wordpress.

**Comment by mrjarbenne** [comment]
In the Azure AD setting page in WordPress, I would check to ensure that new users are being auto-provisioned. This way, once a user is authenticated through Azure, if they don't already exist in the WordPress user database, their username/profile is auto-created: 

![2019-09-30_21-26-24](https://user-images.githubusercontent.com/480667/65927796-23cbc800-e3c9-11e9-9f43-888f6783a9f6.png)

**Comment by psignoret** [comment]
Both @tibricel and @mrjarbenne's statements are accurate. This plugin does not require Azure AD Premium, and if you expect WordPress users to be created automatically when the user who signed in with Azure AD is not matched to an existing user in WordPress, you need to enable that option. Otherwise, you need to ensure that the user does already exist in WordPress, and matches the the signed-in user.
