### ISSUE TITLE
ERROR: Could not get an access token to Microsoft Graph. 

### ISSUE THREAD

**Issue by MaximusPa** [psignoret/aad-sso-wordpress#244]
AADSTS900432: Confidential Client is not supported in Cross Cloud request.
I believe this is related to authority host endpoints.
How do I make this work in GovCloud?

**Comment by psignoret** [comment]
Sorry I missed this issue when you opened it originally. Leaving a response here in case someone else comes across the same question.

To use this plugin with an Azure AD tenant in U.S. Gov cloud, you need to update the "OpenID Connect configuration endpoint" value in the settings (at the bottom, under "Advanced") to point to `https://login.microsoftonline.us/...` instead of `https://login.microsoftonline.com/...`. 

(For other clouds, use the value listed at https://docs.microsoft.com/azure/active-directory/develop/authentication-national-cloud#azure-ad-authentication-endpoints.)
