### ISSUE TITLE
How to refresh Access Token?

### ISSUE THREAD

**Issue by amarvora** [psignoret/aad-sso-wordpress#264]
Hello 

I am using Graph API by "Access Token" from session. But if I keep my page idle for a while and then after If I refresh the page then it gives error of "Authorization" in Graph API and it's due to access token is expire. I would like to know, How I can refresh the access token silently? Is there any way to re-generate the access token and re-store back to session?

**Comment by psignoret** [comment]
Apologies for the delayed response.

Following a successful sign-in, Azure AD does provide a refresh token, along with the access token and ID tokens. This plugin does not current provide an intentional interface to either the access token or the refresh token.

(You could, at your own risk, modify your version of the plugin to grab the `refresh_token` parameter of the token response (e.g. right around where the `access_token` value is placed in a `$_SESSION` variable, and use that for your future refreshes. I recommend being very careful about where and how you store refresh tokens, as they have the potential of enabling persistent access is someone were able to get access to your site deployment or infrastructure.)
