### ISSUE TITLE
Unable to activate: Fatal Error Cannot redeclare class JWT

### ISSUE THREAD

**Issue by FrogStoneMedia** [psignoret/aad-sso-wordpress#28]
Fatal error: Cannot redeclare class JWT in /wp-content/plugins/aad-sso-wordpress/lib/php-jwt/Authentication/JWT.php on line 17

Upon activating the plugin, this error comes up.

Using WordPress 4.2.2

Also using Zendesk with SSO activated: https://wordpress.org/plugins/zendesk/

**Comment by psignoret** [comment]
Apologies for the delay here.

This is happening because both Zendesk and AAD SSO Wordpress both use a class named "JWT" to parse (and validate) the tokens.

I took a look at Zendesk, and it appears they are also using `JWT.php` from [firebase/php-jwt](https://github.com/firebase/php-jwt/), but a much [older version](www.mergely.com/LaENTDL5/) (which does not address [this vulnerability](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/); I've [reported](https://wordpress.org/support/topic/jwtphp-needs-to-be-updated-to-address-vulnerabilities?replies=1#post-7043917) this to them).

Either way, I'll look into changing the class name in `aad-sso-wordpress` to avoid this type of conflict. Expect an update in the next few days.

**Comment by tallbusiness** [comment]
is there any update on this? I am getting the same error. I am a novice but maybe you can just tell where to update and I will make the necessary edits?

**Comment by psignoret** [comment]
This specific issue was fixed in #87, since Zendesk is not using a namespaced version of the `JWT` class. I've created #88 to track finding a better way to avoid the general case of class name collisions when two plugins load the same library.
