### ISSUE TITLE
Matching by email is case sensitive

### ISSUE THREAD

**Issue by HowardvanRooijen** [psignoret/aad-sso-wordpress#30]
Hi,

when testing this out, we discovered that some users with existing accounts in WP had lowercase email addresses, but the email address stored in Azure AD was Proper case... and this failed to log users in.

Other than that - awesome plugin - great work!

**Comment by psignoret** [comment]
Great catch, thanks. Fix, will get done soon.

**Comment by eavonius** [comment]
ETA?

**Comment by psignoret** [comment]
For the longest time, I was unable to reproduce this, but after digging into the code for WordPress' `get_user_by` method (which is used by this plugin to retrieve the user by `login` or by `email`), I've concluded that this is most likely dependent on your database, table and column collation.

The default collation is `utf8_general_ci`, which is case-insensitive. I suspect you may have installed WordPress using a different collation which is case-sensitive. (I was able to reproduce this issue by testing the plugin in a fresh WordPress installation that used `utf8_bin`, which is a case-sensitive collation.)

Default WordPress installations will have the following in `wp-config.php`:

```php
/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');
```

During the initial WordPress installation, this will result in the default collation of `utf8_general_ci`, which is **c**ase-**i**nsensitive (that's what `_ci` refers to). This means that when WordPress issues the MySQL query used to look up a user by email, such as:

```sql
SELECT * FROM `wp_users` WHERE `email` = 'User@ExamPle.coM';
```

It would match a user where `email` was actually `user@example.com` (in lower case). However, if you installed WordPress with a different default collation, such as:

```php
/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', 'utf8_bin');
```

The SQL query above would *not* have matched a user with an email address set to `user@example.com`, because `utf8_bin` is a case-sensitive collation.

So, what can you do?

Unfortunately, simply changing the value in `wp-config.php` will not have an effect, as the collation is stored at the database, table and column level, and this is set during the WordPress installation process. However, there are a couple options to consider:

#### Option 1: Make them match

**Warning: Always backup your WordPress database before attempting any manual changes to it!**

On the WordPress side, you can manually change everyone's email address to be lower case. If you have a significant number of users, you can do this directly on the database:

```sql
/* Makes all WordPress users' emails lower case */
UPDATE `wp_users` SET `user_email` = LOWER(`user_email`);
```

On the Azure AD side, you can change everyone's UserPrincipalName without affecting their ability to sign in (username is case-insensitive in Azure AD). Again, you can do this manually, in the Azure portal, or you could script it using [Azure AD PowerShell](https://msdn.microsoft.com/en-us/library/jj151815.aspx#bkmk_installmodule):

**Warning: Always test Azure AD PowerShell cmdlets and scripts on non-production users first!**

```powershell
# Changes all Azure AD users' UserPrincipalName to lower case
Get-MsolUser -All | % {
    Set-MsolUserPrincipalName -ObjectId ($_.ObjectID) `
                              -NewUserPrincipalName ($_.UserPrincipalName.ToLower())
}
```

#### Option 2: Change the collation

**Warning: Always backup your WordPress database before attempting any manual changes to it!**

With this option, you would simply change the collation of the `user_email` (and optionally, the `user_login`) columns of the `wp_users` table of your WordPress database.

```sql
/* Changes collation of email column */
ALTER TABLE `wp_users` CHANGE `user_email` `user_email` VARCHAR(100) CHARSET utf8 COLLATE utf8_general_ci DEFAULT '' NOT NULL;
```

#### More reading

* https://codex.wordpress.org/Glossary#Collation
* https://codex.wordpress.org/Converting_Database_Character_Sets
* http://dev.mysql.com/doc/refman/5.0/en/charset-general.html
