### ISSUE TITLE
ERROR: Invalid id_token

### ISSUE THREAD

**Issue by jdadon32** [psignoret/aad-sso-wordpress#34]
I have the plugin installed on my site for more than 6 months, this week we started to receive the following error when trying to login 
ERROR: Invalid id_token. Cannot handle token prior to 2015-12-01T10:39:32+0000
(the time stamp is when you tried to login)

I haven't made any changes to the server or the application in Azure. 

Why is this happening but more important how do i fix this ???

Thanks
Josef

**Comment by psignoret** [comment]
It would appear you are getting a token from Azure AD that is not considered valid because the current time is before the time given by the `nbf` (not before) claim or the `iat` (issued at) claims in the ID Token. (See [line 81](https://github.com/psignoret/aad-sso-wordpress/blob/1cbc1de5d89b1e987aeb346e907a709358b4c1d3/lib/php-jwt/Authentication/JWT.php#L81) and [line 89](https://github.com/psignoret/aad-sso-wordpress/blob/1cbc1de5d89b1e987aeb346e907a709358b4c1d3/lib/php-jwt/Authentication/JWT.php#L89) of JWT.php to see the code).

The usual cause for this is clock skew, where your server's clock has fallen far enough behind that it's definition of "now" is actually a few minutes ago, which makes it think that the token is not valid yet.

However, I'm still abit surprised to see this, since Azure AD normally includes a 5-minute buffer in both the `iat` and `nbf` claims (in other words, they're both 5 minutes in the past).

If you compare the time displayed in the error message to the current time as shown at http://time.is/UTC, do you see the 5 minute difference?

**Comment by jdadon32** [comment]
Yes i can see the time difference in my case its almost 10 minutes.

what is the best way to get the time sorted on a Linux VM ?

Thanks

**Comment by jdadon32** [comment]
Found it just had to install NTP on my VM and correct the time on the server 
all working now thanks :)

**Comment by psignoret** [comment]
Great!
