### ISSUE TITLE
ANTIFORGERY_ID debacle

### ISSUE THREAD

**Issue by gsisaratsidis** [psignoret/aad-sso-wordpress#63]
I feel like I have all the settings set properly. Two nearly identical instances: one works fine, the other is having issues. The two Azure applications are set-up identically. I am very open to ideas and suggestions.

Consistently getting:
ANTIFORGERY_ID mismatch. Expecting {5001CD3E-DD9E-7999-EECA-14B6A9F6606D}

**Comment by psignoret** [comment]
Are you running a single instance? Or load-balancing multiple instances?

**Comment by gsisaratsidis** [comment]
Running a single instance.
One instance is located on our dev server with a 172.x address and that one is working fine.
The instance on shared hosting is getting the above referenced error without fail. They are configured as two separate applications but almost identical (other than the obvious, URLs etc).

**Comment by psignoret** [comment]
What server stack are you using? (Apache? IIS?) Do you have Session support enabled for PHP?

**Comment by gsisaratsidis** [comment]
Apache 2.2.15 on CentOS 6.7 ; Session support enabled.

**Comment by psignoret** [comment]
Did you cover the basics (completely clean browser session, disable other plugins, etc.)? If so, can you shoot me an email to philippe.signoret@outlook.com with the details of your blog?

**Comment by gsisaratsidis** [comment]
I have covered these, unfortunately. I have e-mailed as requested. Thank you for your help!

**Comment by psignoret** [comment]
For future reference, there were two issues:

1. The state (ANTIFORGERY_ID) value was being re-generated due to a mis-behaving plugin injecting, as CSS, a background image URL as: `url('')`. This resulted in a second request to `wp_login.php`, making the original state value invalid. Work-around for the plugin in question is to use a transparent 1-pixel image instead of no image at all. More details and possible hardening on the AADSSO side tracked with issue #65.
2. The public key used to verify the ID Token was being retrieved with PHP's `file_get_contents()`, which requires `allow_url_fopen=1`. This is a bug, AADSSO should be using `wp_remote_get()` instead, fix tracked with issue #64.

**Comment by psignoret** [comment]
* Reported issue at: https://wordpress.org/support/topic/empty-background-image-results-in-duplicate-loading-of-wp-loginphp
* Trac ticket with patch for fix: https://plugins.trac.wordpress.org/ticket/2488

**Comment by woodwardmatt** [comment]
Just to note for anyone else experiencing this, I have also seen the same behavior under the scenario where you may display the login link in multiple places e.g. in my case on a sidebar, then as part of the content of a page. (This was under a Buddypress implementation)

I just removed the sidebar for that particular page, but general rule seems to point to one instance of the link per page :) Hope that helps somebody :)

**Comment by psignoret** [comment]
Thanks, @woodwardmatt. Another reason to make the anti-forgery generation more robust. Tracking this via #65.
