### ISSUE TITLE
Q: Does this work for Wordpress Multisite?

### ISSUE THREAD

**Issue by woodwardmatt** [psignoret/aad-sso-wordpress#75]
Hi there,

Just found your plugin and was wondering if it works with Wordpress under a Multisite configuration?

Our flow is usually:

1. User creates a user account.
2. User is directed to the child site setup admin pages to create their own site.
3. User's site is provisioned and can be accessed by the user.

This is currently all working with the standard alone user accounts but very keen to see if I can integrate azure ad authentication.

Any thoughts?

**Comment by psignoret** [comment]
I have tested this with multi site, at least for the  basic scenarios.

Give it a shot and let me knowing you have any issues, your scenario sounds pretty interesting.

**Comment by woodwardmatt** [comment]
Hey @psignoret - thanks for the response!

I've done some initial testing and all is looking good so far. I've only activated the plugin on the parent / root site (as I'm figuring the child sites wouldn't want / need to setup individual settings - all sites will use a single client app id from Azure AD). This basically then means all child sites need to login via the parent site to be able to use the Office 365 login, and then be redirected to their own site's dashboard. 

All looking good so far, I have a few more scenarios to test today then will be able to give you a full update :)

**Comment by woodwardmatt** [comment]
Hey @psignoret - Have put this through a few different scenarios and its held up very well, certainly works with WordPress Multisite without any issues from my side as far as I know :)

The mapping back to standalone users by email is working well, I haven't had to use groups in my scenario so can't make any claims there.

Have you had any thoughts to have an option to "pass a prompt=admin_consent parameter to the authorize endpoint to force the administrator consent experience" where organisations want to configure organisation wide approval for an app setup in Azure AD?

I'd see this as a separate sign in link almost, or perhaps surfaced as a shortcode that can be placed as content on a separate post / page so the context of using could be explained a little better.

Just a thought :)

Awesome work!

**Comment by woodwardmatt** [comment]
The reference for the admin endpoint idea can be found [here](https://azure.microsoft.com/en-us/documentation/articles/active-directory-integrating-applications/#overview-of-the-consent-framework) under "Triggering the Azure AD consent framework at runtime".

**Comment by psignoret** [comment]
@woodwardmatt Going through open issues here, and realized I never followed up with you here, I apologize.

Adding `prompt=admin_consent` for all sign ins would not be a good approach, as this would (a) fail for any non-admin with a "AADSTS90093: Does not have access to consent.", and (b) re-prompt admins every time the signed in.

However, the idea of generating a link that directory admins can use (or that can be shared with directory admins) to grant consent on behalf of the organization, is a great idea. I think this would best be implemented as a query parameter in the `wp-login` page (so that non-admins can get a link that they can share with their directory admins when they ask them to consent).

I've created #86 to track this new feature.
