### ISSUE TITLE
Assign AD group to Wordpress Group

### ISSUE THREAD

**Issue by mike12121212** [psignoret/aad-sso-wordpress#80]
Currently a user is assigned to a WordPress Role based on their Azure AD group.  Using this plugin: [https://wordpress.org/plugins/contexture-page-security](https://wordpress.org/plugins/contexture-page-security)/, I have also created groups in WordPress that I would like to assign a user to automatically based on their Azure AD group.  How can I accomplish this?

**Comment by psignoret** [comment]
Since WordPress does not natively have any concept of a "group", this is not high on the list of priorities for this plugin. The main reason is that there are multiple WP plugins that introduce a concept of "groups", but they are not all implemented the same.

One approach that I would consider is to make some information about the user available to other plugins (e.g. the list of Azure AD group memberships). The other plugins (e.g. Page Security and Membership, or a dedicated plugin just for this) could then make use of this and apply their own business logic (e.g. assign the user to whatever they understand to be a group).

I'm keeping this issue open, as the idea itself is interesting and certainly work keeping in mind.

**Comment by mike12121212** [comment]
I appreciate your response.
