### ISSUE TITLE
Azure Signing Key Rollover?

### ISSUE THREAD

**Issue by richthomsen** [psignoret/aad-sso-wordpress#81]
Is there support or plans for Key Rollover for the SSO plug-in?   If I understand this correctly, I am going to have to manually update all the keys for (many) WordPress sites that are using this SSO method.  Can you help?

https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/?WT.mc_id=azurebg_email_Trans_1150_Azure_AD_Certificate_Rollover

**Comment by psignoret** [comment]
No, you don't have to do anything.

This plugin does verify the signature of the ID Token*, and it does it by reloading the signing keys (from the [JSON Web Key Set document](https://tools.ietf.org/html/rfc7517)) every time a user signs in. This means that as soon as the new signing keys are used by Azure AD, the plugin will already be verifying the token signature with the new signing keys. (If you're curious, see [`validate_id_token(...)` in AuthorizationHelper.php](https://github.com/psignoret/aad-sso-wordpress/blob/master/AuthorizationHelper.php#L104) for the details.)

Since fetching the keys (which rarely change) every single time soneone signs in is a bit of overkill, there is a pending work item to cache the signing keys, but rest assured, when that is implemented, it will account for key rollovers, both planned and emergency.

*Technically, ID Token signature verification is not required in the OpenID Connect Authorization Code Flow, which this plugin implements, but we do it anyway just for thoroughness. (See [OpenID Connect 3.1.3.7 ID Token Validation](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) for more.)

**Comment by psignoret** [comment]
Note: The other signed token involved in this plugin is the Access Token (used to fetch a user's group memberships from the Azure AD Graph API). The Access Token signature is validated by the Azure AD Graph API itself (it's just an opaque blob of text to the plugin). The Azure AD Graph API already knows how to deal with key rollovers.
